=== Mortimer666/EPAM-Task2XML/src/test/resources/medicines.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.com/medicines"
        xmlns:tns="http://www.example.com/medicines" elementFormDefault="qualified">
    <element name="medicines">
        <complexType>
            <sequence>
                <element ref="tns:medicine" minOccurs="4" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="medicines">
        <sequence>
            <element name="countryOfOrigin">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="BELARUS"/>
                        <enumeration value="RUSSIA"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="price" type="double"/>
        </sequence>
        <attribute name="id" type="tns:id" use="required"/>
        <attribute name="name" type="string"/>
    </complexType>
    <simpleType name="id">
        <restriction base="ID">
            <pattern value="(ID-)[0-9]{5}"/>
        </restriction>
    </simpleType>
    <element name="medicine" type="tns:medicines" abstract="true"/>
    <element name="antibiotics" type="tns:antibiotics" substitutionGroup="tns:medicine"/>
    <complexType name="antibiotics">
        <complexContent>
            <extension base="tns:medicines">
                <sequence>
                    <element name="groupOfAntibiotics" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <element name="analgesics" type="tns:analgesics" substitutionGroup="tns:medicine"/>
    <complexType name="analgesics">
        <complexContent>
            <extension base="tns:medicines">
                <sequence>
                    <element name="isSteroid" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
</schema>

=== Mortimer666/EPAM-Task2XML/src/test/resources/medicines.xml
<?xml version="1.0" encoding="UTF-8" ?>
<medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.example.com/medicines"
           xsi:schemaLocation="http://www.example.com/medicines medicines.xsd">
    <antibiotics id='ID-12523'>
        <countryOfOrigin>BELARUS</countryOfOrigin>
        <price>25.13</price>
        <groupOfAntibiotics>Tetracyclines</groupOfAntibiotics>
    </antibiotics>
    <antibiotics id='ID-12896' name='Augmentin'>
        <countryOfOrigin>RUSSIA</countryOfOrigin>
        <price>13.16</price>
        <groupOfAntibiotics>Penicillins</groupOfAntibiotics>
    </antibiotics>
    <analgesics id='ID-13158' name='Buprenorphine'>
        <countryOfOrigin>RUSSIA</countryOfOrigin>
        <price>62.95</price>
        <isSteroid>No</isSteroid>
    </analgesics>
    <analgesics id='ID-13673'>
        <countryOfOrigin>BELARUS</countryOfOrigin>
        <price>56.44</price>
        <isSteroid>Yes</isSteroid>
    </analgesics>
</medicines>
